SET search_path = MIMIC2V26, pg_catalog;
ALTER TABLE "d_patients" ADD PRIMARY KEY ("subject_id");
ALTER TABLE "d_caregivers" ADD PRIMARY KEY ("cgid");
ALTER TABLE "poe_order" ADD PRIMARY KEY ("poe_id");
CREATE INDEX poe_order_o4 ON "poe_order" ("icustay_id");
CREATE INDEX poe_order_o1 ON "poe_order" ("subject_id","hadm_id");
CREATE INDEX poe_order_o3 ON "poe_order" ("hadm_id");
CREATE INDEX poe_order_o2 ON "poe_order" ("subject_id");
CREATE INDEX a_meddurations_o1 ON "a_meddurations" ("cuid");
CREATE UNIQUE INDEX a_meddurations_pk ON "a_meddurations" ("subject_id","itemid","elemid","starttime");
CREATE INDEX a_meddurations_o4 ON "a_meddurations" ("icustay_id");
CREATE INDEX a_meddurations_o2 ON "a_meddurations" ("subject_id");
CREATE INDEX a_meddurations_o3 ON "a_meddurations" ("itemid");
ALTER TABLE "d_labitems" ADD PRIMARY KEY ("itemid");
CREATE INDEX additives_o6 ON "additives" ("cgid");
CREATE INDEX additives_o4 ON "additives" ("itemid");
CREATE INDEX additives_o2 ON "additives" ("subject_id");
CREATE INDEX additives_o1 ON "additives" ("cuid");
CREATE INDEX additives_o5 ON "additives" ("icustay_id");
CREATE INDEX additives_o3 ON "additives" ("ioitemid");
CREATE INDEX poe_med_o1 ON "poe_med" ("poe_id");
CREATE INDEX totalbalevents_o3 ON "totalbalevents" ("itemid");
CREATE INDEX totalbalevents_o5 ON "totalbalevents" ("cgid");
CREATE INDEX totalbalevents_o1 ON "totalbalevents" ("cuid");
CREATE INDEX totalbalevents_o4 ON "totalbalevents" ("icustay_id");
CREATE INDEX totalbalevents_o2 ON "totalbalevents" ("subject_id");
ALTER TABLE "d_meditems" ADD PRIMARY KEY ("itemid");
CREATE INDEX a_iodurations_o1 ON "a_iodurations" ("cuid");
CREATE INDEX a_iodurations_o2 ON "a_iodurations" ("subject_id");
CREATE UNIQUE INDEX a_iodurations_pk ON "a_iodurations" ("subject_id","itemid","elemid","starttime");
CREATE INDEX a_iodurations_o3 ON "a_iodurations" ("itemid");
CREATE INDEX noteevents_o6 ON "noteevents" ("cgid");
CREATE INDEX noteevents_o1 ON "noteevents" ("cuid");
CREATE INDEX noteevents_o4 ON "noteevents" ("hadm_id");
CREATE INDEX noteevents_o2 ON "noteevents" ("subject_id");
CREATE INDEX noteevents_o5 ON "noteevents" ("category");
CREATE INDEX noteevents_o3 ON "noteevents" ("icustay_id");
CREATE INDEX ioevents_o6 ON "ioevents" ("cgid");
CREATE INDEX labevents_o4 ON "labevents" ("itemid");
CREATE INDEX labevents_o2 ON "labevents" ("hadm_id");
CREATE INDEX labevents_o1 ON "labevents" ("subject_id");
CREATE INDEX labevents_o3 ON "labevents" ("icustay_id");
CREATE INDEX labevents_o5 ON "labevents" ("icustay_id","itemid");
CREATE INDEX chartevents_o4 ON "chartevents" ("itemid");
CREATE INDEX chartevents_o2 ON "chartevents" ("subject_id","itemid");
CREATE INDEX chartevents_o5 ON "chartevents" ("icustay_id");
CREATE INDEX chartevents_o1 ON "chartevents" ("cuid");
CREATE INDEX chartevents_o3 ON "chartevents" ("subject_id");
CREATE INDEX chartevents_o6 ON "chartevents" ("charttime");
CREATE INDEX chartevents_o7 ON "chartevents" ("cgid");
ALTER TABLE "procedureevents" ADD PRIMARY KEY ("subject_id","hadm_id","sequence_num");
CREATE INDEX procedureevents_o2 ON "procedureevents" ("itemid");
CREATE INDEX procedureevents_o1 ON "procedureevents" ("hadm_id");
ALTER TABLE "d_codeditems" ADD PRIMARY KEY ("itemid");
ALTER TABLE "d_demographicitems" ADD PRIMARY KEY ("itemid");
CREATE INDEX comorbidity_o3 ON "comorbidity_scores" ("subject_id","hadm_id");
CREATE INDEX comorbidity_o2 ON "comorbidity_scores" ("hadm_id");
CREATE INDEX comorbidity_o1 ON "comorbidity_scores" ("subject_id");
ALTER TABLE "admissions" ADD PRIMARY KEY ("hadm_id");
CREATE INDEX admissions_o1 ON "admissions" ("subject_id");
ALTER TABLE "demographicevents" ADD PRIMARY KEY ("subject_id","hadm_id","itemid");
CREATE INDEX demographicevents_o1 ON "demographicevents" ("hadm_id");
CREATE INDEX demographicevents_o2 ON "demographicevents" ("itemid");
ALTER TABLE "d_careunits" ADD PRIMARY KEY ("cuid");
CREATE UNIQUE INDEX icustay_detail_pk ON "icustay_detail" ("icustay_id");
CREATE UNIQUE INDEX icustay_detail_u1 ON "icustay_detail" ("subject_id","icustay_id");
CREATE INDEX a_chartdurations_o3 ON "a_chartdurations" ("icustay_id");
CREATE INDEX a_chartdurations_o1 ON "a_chartdurations" ("cuid");
CREATE INDEX a_chartdurations_o4 ON "a_chartdurations" ("itemid");
CREATE INDEX a_chartdurations_o2 ON "a_chartdurations" ("subject_id");
CREATE UNIQUE INDEX d_chartitems_detail_u1 ON "d_chartitems_detail" ("itemid");
CREATE UNIQUE INDEX d_chartitems_detail_u2 ON "d_chartitems_detail" ("itemid","label","label_lower","category");
CREATE INDEX d_chartitems_detail_o1 ON "d_chartitems_detail" ("label_lower");
ALTER TABLE "drgevents" ADD PRIMARY KEY ("subject_id","hadm_id","itemid");
CREATE INDEX drgevents_o2 ON "drgevents" ("itemid");
CREATE INDEX drgevents_o1 ON "drgevents" ("hadm_id");
CREATE INDEX drgevents_o32 ON "drgevents" ("subject_id");
ALTER TABLE "icustayevents" ADD PRIMARY KEY ("icustay_id");
CREATE UNIQUE INDEX icustayev_u1 ON "icustayevents" ("subject_id","intime");
CREATE INDEX icustayevents_o4 ON "icustayevents" ("first_careunit");
CREATE INDEX icustayevents_o3 ON "icustayevents" ("last_careunit");
CREATE INDEX icustayevents_o1 ON "icustayevents" ("intime");
CREATE INDEX icustayevents_o2 ON "icustayevents" ("outtime");
ALTER TABLE "d_chartitems" ADD PRIMARY KEY ("itemid");
CREATE INDEX icd9_o2 ON "icd9" ("hadm_id");
CREATE INDEX icu9_o1 ON "icd9" ("subject_id");
ALTER TABLE "censusevents" ADD PRIMARY KEY ("census_id");
CREATE INDEX censusevents_o4 ON "censusevents" ("careunit");
CREATE INDEX censusevents_01 ON "censusevents" ("destcareunit");
CREATE INDEX censusevents_u1 ON "censusevents" ("subject_id","intime");
CREATE INDEX censusevents_o3 ON "censusevents" ("icustay_id");
CREATE INDEX censusevents_o2 ON "censusevents" ("subject_id");
CREATE INDEX microbiologyevents_o3 ON "microbiologyevents" ("subject_id");
CREATE INDEX microbiologyevents_o1 ON "microbiologyevents" ("ab_itemid");
CREATE INDEX microbiologyevents_o4 ON "microbiologyevents" ("org_itemid");
CREATE INDEX microbiologyevents_o5 ON "microbiologyevents" ("spec_itemid");
CREATE INDEX microbiologyevents_o2 ON "microbiologyevents" ("hadm_id");
CREATE INDEX icustay_days_o1 ON "icustay_days" ("icustay_id","seq");
CREATE INDEX medevents_o3 ON "medevents" ("itemid");
CREATE INDEX medevents_o5 ON "medevents" ("icustay_id");
CREATE INDEX medevents_o2 ON "medevents" ("subject_id");
CREATE UNIQUE INDEX medevents_pk ON "medevents" ("subject_id","itemid","charttime","elemid");
CREATE INDEX medevents_o6 ON "medevents" ("cgid");
CREATE INDEX medevents_o4 ON "medevents" ("solutionid");
CREATE INDEX medevents_o1 ON "medevents" ("cuid");
ALTER TABLE "d_ioitems" ADD PRIMARY KEY ("itemid");
CREATE INDEX deliveries_o1 ON "deliveries" ("cuid");
CREATE INDEX deliveries_o3 ON "deliveries" ("ioitemid");
CREATE INDEX deliveries_o5 ON "deliveries" ("cgid");
CREATE INDEX deliveries_o4 ON "deliveries" ("icustay_id");
CREATE UNIQUE INDEX deliveries_pk ON "deliveries" ("subject_id","ioitemid","charttime","elemid");
CREATE INDEX deliveries_o2 ON "deliveries" ("subject_id");
ALTER TABLE "poe_order" ADD CONSTRAINT "poe_order_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "poe_order" ADD CONSTRAINT "poe_order_fk_admiss" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "poe_order" ADD CONSTRAINT "poe_order_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_meddurations" ADD CONSTRAINT "a_meddur_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_meddurations" ADD CONSTRAINT "a_meddur_fk_d_medite" FOREIGN KEY ("itemid") REFERENCES "d_meditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_meddurations" ADD CONSTRAINT "a_meddur_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_meddurations" ADD CONSTRAINT "a_meddur_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_d_medite" FOREIGN KEY ("itemid") REFERENCES "d_meditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_d_ioitem" FOREIGN KEY ("ioitemid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "additives" ADD CONSTRAINT "additives_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "poe_med" ADD CONSTRAINT "poe_med_poe_order_fk1" FOREIGN KEY ("poe_id") REFERENCES "poe_order" ("poe_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "totalbalevents" ADD CONSTRAINT "totalbal_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "totalbalevents" ADD CONSTRAINT "totalbal_fk_d_ioitem" FOREIGN KEY ("itemid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "totalbalevents" ADD CONSTRAINT "totalbal_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "totalbalevents" ADD CONSTRAINT "totalbal_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "totalbalevents" ADD CONSTRAINT "totalbal_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_iodurations" ADD CONSTRAINT "a_iodura_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_iodurations" ADD CONSTRAINT "a_iodura_fk_d_ioitem" FOREIGN KEY ("itemid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_iodurations" ADD CONSTRAINT "a_iodura_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_iodurations" ADD CONSTRAINT "a_iodura_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "noteevents" ADD CONSTRAINT "noteeven_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "noteevents" ADD CONSTRAINT "noteeven_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "noteevents" ADD CONSTRAINT "noteeven_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "noteevents" ADD CONSTRAINT "noteeven_fk_adm" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "noteevents" ADD CONSTRAINT "noteeven_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk_d_ioitem" FOREIGN KEY ("itemid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk2_d_ioitem" FOREIGN KEY ("altid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ioevents" ADD CONSTRAINT "ioevents_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "labevents" ADD CONSTRAINT "labevents_fk_subject_id" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "labevents" ADD CONSTRAINT "labevents_fk_itemid" FOREIGN KEY ("itemid") REFERENCES "d_labitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "labevents" ADD CONSTRAINT "labevents_fk_hadm_id" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "labevents" ADD CONSTRAINT "labevents_fk_icustay_id" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chartevents" ADD CONSTRAINT "charteve_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chartevents" ADD CONSTRAINT "charteve_fk_d_charti" FOREIGN KEY ("itemid") REFERENCES "d_chartitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chartevents" ADD CONSTRAINT "charteve_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chartevents" ADD CONSTRAINT "charteve_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "chartevents" ADD CONSTRAINT "charteve_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "procedureevents" ADD CONSTRAINT "procedureevents_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "procedureevents" ADD CONSTRAINT "procedureevents_fk_adm" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "procedureevents" ADD CONSTRAINT "procedureevents_fk_d_coded" FOREIGN KEY ("itemid") REFERENCES "d_codeditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "admissions" ADD CONSTRAINT "admissions_fk_d_pati" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "demographicevents" ADD CONSTRAINT "demographicevents_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "demographicevents" ADD CONSTRAINT "demographicevents_fk_admit" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "demographicevents" ADD CONSTRAINT "demographicevents_fk_itemid" FOREIGN KEY ("itemid") REFERENCES "d_demographicitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_chartdurations" ADD CONSTRAINT "a_chartd_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_chartdurations" ADD CONSTRAINT "a_chartd_fk_d_charti" FOREIGN KEY ("itemid") REFERENCES "d_chartitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_chartdurations" ADD CONSTRAINT "a_chartd_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "a_chartdurations" ADD CONSTRAINT "a_chartd_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "drgevents" ADD CONSTRAINT "drgevents_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "drgevents" ADD CONSTRAINT "drgevents_fk_admit" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "drgevents" ADD CONSTRAINT "drgevents_fk_itemid" FOREIGN KEY ("itemid") REFERENCES "d_codeditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "icustayevents" ADD CONSTRAINT "icustayev_fk2_d_careu" FOREIGN KEY ("last_careunit") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "icustayevents" ADD CONSTRAINT "icustayev_fk_d_pat" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "icustayevents" ADD CONSTRAINT "icustayev_fk_d_careu" FOREIGN KEY ("first_careunit") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "icd9" ADD CONSTRAINT "icd9_fk_admiss" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "icd9" ADD CONSTRAINT "icd9_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "censusevents" ADD CONSTRAINT "censusev_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "censusevents" ADD CONSTRAINT "censusev_fk_d_careun" FOREIGN KEY ("careunit") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "censusevents" ADD CONSTRAINT "censusev_fk2_d_careun" FOREIGN KEY ("destcareunit") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "censusevents" ADD CONSTRAINT "censusev_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "microbiologyevents" ADD CONSTRAINT "microbioev_fk_d_patients" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "microbiologyevents" ADD CONSTRAINT "microbioev_fk_admissions" FOREIGN KEY ("hadm_id") REFERENCES "admissions" ("hadm_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "microbiologyevents" ADD CONSTRAINT "microbioev_spec_fk_d_coded" FOREIGN KEY ("spec_itemid") REFERENCES "d_codeditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "microbiologyevents" ADD CONSTRAINT "microbioev_org_fk_d_coded" FOREIGN KEY ("org_itemid") REFERENCES "d_codeditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "microbiologyevents" ADD CONSTRAINT "microbioev_ab_fk_d_coded" FOREIGN KEY ("ab_itemid") REFERENCES "d_codeditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevent_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevent_fk2_d_medite" FOREIGN KEY ("solutionid") REFERENCES "d_meditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevent_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevent_fk_d_medite" FOREIGN KEY ("itemid") REFERENCES "d_meditems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevent_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "medevents" ADD CONSTRAINT "medevents_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveri_fk_d_patien" FOREIGN KEY ("subject_id") REFERENCES "d_patients" ("subject_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveri_fk_d_ioitem" FOREIGN KEY ("ioitemid") REFERENCES "d_ioitems" ("itemid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveri_fk_d_caregi" FOREIGN KEY ("cgid") REFERENCES "d_caregivers" ("cgid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveri_fk_d_careun" FOREIGN KEY ("cuid") REFERENCES "d_careunits" ("cuid") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "deliveries" ADD CONSTRAINT "deliveri_fk_icustay" FOREIGN KEY ("icustay_id") REFERENCES "icustayevents" ("icustay_id") ON DELETE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
